import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:pointycastle/digests/sha256.dart';

/// A recurring transaction rule.
///
/// Frequency is expressed as months (float): 0.5 = biweekly, 1 = monthly,
/// 3 = quarterly, 12 = annual.
class RecurringRule {
  final String id;
  final String name;
  final String kind; // TransactionKind as string
  final int amount; // paise
  final String accountId;
  final String? toAccountId; // for transfers
  final double frequencyMonths;
  final DateTime startDate;
  final DateTime? endDate;
  final bool isPaused;
  final DateTime? pausedAt;
  final DateTime? lastExecutedDate;
  final double annualEscalationRate; // e.g. 0.10 for 10%
  final String? categoryId;

  const RecurringRule({
    required this.id,
    required this.name,
    required this.kind,
    required this.amount,
    required this.accountId,
    this.toAccountId,
    required this.frequencyMonths,
    required this.startDate,
    this.endDate,
    required this.isPaused,
    this.pausedAt,
    this.lastExecutedDate,
    this.annualEscalationRate = 0,
    this.categoryId,
  });
}

/// A transaction generated by a recurring rule.
class PendingTransaction {
  final String ruleId;
  final DateTime date;
  final int amount; // paise (may include escalation)
  final String kind;
  final String name;
  final String accountId;
  final String? toAccountId;
  final String? categoryId;

  const PendingTransaction({
    required this.ruleId,
    required this.date,
    required this.amount,
    required this.kind,
    required this.name,
    required this.accountId,
    this.toAccountId,
    this.categoryId,
  });
}

/// Pure recurring transaction scheduler.
///
/// Computes due dates and generates pending transactions based on rules.
/// No DB access — caller provides rules and dates.
class RecurringScheduler {
  RecurringScheduler._();

  /// Computes an idempotent key for a recurring transaction instance.
  ///
  /// Returns `SHA256(ruleId + date.toIso8601String())` as a hex string.
  /// Used to prevent duplicate generation when the scheduler runs multiple times.
  static String computeIdempotentKey(String ruleId, DateTime date) {
    final input = '$ruleId${date.toIso8601String()}';
    final digest = SHA256Digest();
    final bytes = digest.process(Uint8List.fromList(utf8.encode(input)));
    return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  /// Computes all due dates for a rule within [from, until).
  ///
  /// Steps forward from [rule.startDate] by [rule.frequencyMonths],
  /// collecting dates that fall within the window.
  static List<DateTime> computeDueDates({
    required RecurringRule rule,
    required DateTime from,
    required DateTime until,
  }) {
    if (rule.isPaused) return [];

    final effectiveEnd = rule.endDate != null && rule.endDate!.isBefore(until)
        ? rule.endDate!
        : until;

    final dates = <DateTime>[];
    var current = rule.startDate;

    // Step forward from start date by frequency
    while (current.isBefore(effectiveEnd)) {
      if (!current.isBefore(from)) {
        dates.add(current);
      }
      current = _addMonths(current, rule.frequencyMonths);
    }

    return dates;
  }

  /// Computes the escalated amount for a rule at a given date.
  ///
  /// Escalation applies annually from the start date.
  /// Year 1 (startDate to startDate+12m): base amount
  /// Year 2: base * (1 + rate)
  /// Year N: base * (1 + rate)^(N-1)
  static int escalatedAmount({
    required RecurringRule rule,
    required DateTime asOfDate,
  }) {
    if (rule.annualEscalationRate == 0) return rule.amount;

    final yearsElapsed = _yearsBetween(rule.startDate, asOfDate);
    if (yearsElapsed <= 0) return rule.amount;

    return (rule.amount * math.pow(1 + rule.annualEscalationRate, yearsElapsed))
        .round();
  }

  /// Generates pending transactions that haven't been executed yet.
  ///
  /// Uses [rule.lastExecutedDate] as the watermark — only generates
  /// transactions for dates after it. If never executed, generates from
  /// [rule.startDate].
  static List<PendingTransaction> pendingTransactions({
    required RecurringRule rule,
    required DateTime asOfDate,
  }) {
    if (rule.isPaused) return [];

    final from = rule.lastExecutedDate != null
        ? _addMonths(rule.lastExecutedDate!, rule.frequencyMonths)
        : rule.startDate;

    final dueDates = computeDueDates(rule: rule, from: from, until: asOfDate);

    return dueDates.map((date) {
      final amount = escalatedAmount(rule: rule, asOfDate: date);
      return PendingTransaction(
        ruleId: rule.id,
        date: date,
        amount: amount,
        kind: rule.kind,
        name: rule.name,
        accountId: rule.accountId,
        toAccountId: rule.toAccountId,
        categoryId: rule.categoryId,
      );
    }).toList();
  }

  /// Adds fractional months to a date.
  ///
  /// Whole months use calendar addition (preserving day-of-month).
  /// Fractional parts are converted to days (0.5 months ≈ 15 days).
  static DateTime _addMonths(DateTime date, double months) {
    final wholeMonths = months.floor();
    final fractionalDays = ((months - wholeMonths) * 30.44).round();

    var newMonth = date.month + wholeMonths;
    var newYear = date.year;
    while (newMonth > 12) {
      newMonth -= 12;
      newYear++;
    }

    // Clamp day to valid range for the new month
    final maxDay = DateTime(newYear, newMonth + 1, 0).day;
    final newDay = date.day > maxDay ? maxDay : date.day;

    var result = DateTime(newYear, newMonth, newDay);
    if (fractionalDays > 0) {
      result = result.add(Duration(days: fractionalDays));
    }

    return result;
  }

  /// Computes whole years between two dates.
  static int _yearsBetween(DateTime start, DateTime end) {
    var years = end.year - start.year;
    if (end.month < start.month ||
        (end.month == start.month && end.day < start.day)) {
      years--;
    }
    return math.max(0, years);
  }
}
