default_platform(:ios)

platform :ios do
  desc "Build release IPA (no upload)"
  lane :build do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      clean: true,
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Upload to App Store"
  lane :release do
    build
    upload_to_app_store(
      force: true,
      submit_for_review: false,
    )
  end
end
