default_platform(:android)

platform :android do
  desc "Build release AAB"
  lane :build do
    sh("cd ../.. && flutter build appbundle --release")
  end

  desc "Upload to Play Store internal track"
  lane :beta do
    build
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end

  desc "Promote internal to production"
  lane :release do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
    )
  end
end
